Repository silx-kit/fabio, pull requests merged in 2018-06, with the labels that each got.

#209 Clean up capsheader from EDF
  fabio/edfimage.py
  fabio/test/testedfimage.py
Labels: ready to merge

#227 Improve CI scripts
  ci/appveyor.yml
  run_tests.py
Labels: ready to merge

#230 Fix clean up
  fabio/test/testedfimage.py
Labels: ready to merge

#235 Use numpy.frombuffer
  fabio/GEimage.py
  fabio/HiPiCimage.py
  fabio/OXDimage.py
  fabio/TiffIO.py
  fabio/adscimage.py
  fabio/binaryimage.py
  fabio/bruker100image.py
  fabio/brukerimage.py
  fabio/compression.py
  fabio/dm3image.py
  fabio/edfimage.py
  fabio/fit2dimage.py
  fabio/fit2dmaskimage.py
  fabio/kcdimage.py
  fabio/mrcimage.py
  fabio/pixiimage.py
  fabio/pnmimage.py
  fabio/raxisimage.py
  fabio/readbytestream.py
  fabio/tifimage.py
  fabio/utils/pilutils.py
  fabio/xsdimage.py
Labels: ready to merge

#222 221 copy
  fabio/fabioimage.py
  fabio/test/testfabioimage.py
Labels: ready to merge

#233 Fix TIFF image using RGB LUT
  fabio/TiffIO.py
  fabio/test/testtifimage.py
  fabio/tifimage.py
  fabio/utils/pilutils.py
Labels: work in progress

#239 Remove URL from openimage
  fabio/openimage.py
Labels: bug
