Repository silx-kit/fabio, pull requests merged in 2020-04, with the labels that each got.

#371 mistake tobytes vs tostring
  fabio/openimage.py
Labels: bug

#378 Fix BytesIO
  fabio/openimage.py
  fabio/test/test_fabio.py
Labels: bug, ready to merge

#380 Clean up test
  fabio/test/codecs/__init__.py
  fabio/test/codecs/test_edfimage_expg.py
  fabio/test/codecs/test_esperantoimage.py
  fabio/test/test_agi_bitfield.py
  fabio/test/test_all.py
  fabio/test/test_compression.py
  fabio/test/test_fabio_convert.py
  fabio/test/test_fabio_image.py
  fabio/test/test_filenames.py
  fabio/test/test_header_not_singleton.py
  fabio/test/test_open_header.py
  fabio/test/test_open_image.py
Labels: enhancement, ready to merge

#382 Declare only python3 comparibility
  setup.py
Labels: enhancement, ready to merge

#383 366 debian patches
  fabio/compression/compression.py
  setup.py
Labels: ready to merge
